<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/jeyups7xy/image/upload/v1554346999/IMG_20190131_071320.jpg" alt="Oyebamiji Jeremiah">
                        <h6>Oyebamiji Jeremiah</h6>
                        <p>Fullstack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/PstFemiO" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/O-Jeremiah" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@PstFemiO" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                            So glad to delve into software development to satisfy my desire to impact the world with technology.
                            I enjoy the learning and the support from others. Music and me, always fun coding!
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
